services:
  backend:
    build:
      context: ./server
    image: opendevlo-server
    container_name: opendevlo-server
    ports:
      - "${PORT_B}:${PORT_B}"
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DB_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      PORT: ${PORT_B}
    depends_on:
      - postgresDb
    volumes:
      - ./server:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT_B}/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  frontend:
    build:
      context: ./client
    image: opendevlo-client
    container_name: opendevlo-client
    ports:
      - "${PORT_F}:${PORT_F}"
    depends_on:
      - backend
    volumes:
      - ./client:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT_F}/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  postgresDb:
    image: postgres
    container_name: opendevlo-postgres
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  db_data:
    driver: local
